name: deploy-angular-app-on-s3
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        working-directory: ./TheBookIndex.Web
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "ap-southeast-2"
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Build Application
        run: npm run buildprod
        working-directory: ${{env.working-directory}}
      - name: Sync To AWS S3 Bucket
        run: aws s3 sync dist/TheBookIndex s3://the-book-index-angular-app
        working-directory: ${{env.working-directory}}
      - name: Invalidate Cloudfront Distribution
        run: aws cloudfront create-invalidation --distribution-id E1WAVIX9Z7GAG2 --paths "/" "/*"
        working-directory: ${{env.working-directory}}
